# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/mrrihan-604/Project1/blob/main/Data%20Visualization.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------------
# STEP 1: Load Dataset
# -----------------------------------

df = pd.read_csv("house_price_prediction_dataset.csv")

print("Dataset Loaded Successfully!\n")

# Display first 5 rows
print(df.head())

# Dataset information
print("\nDataset Information:")
print(df.info())

# -----------------------------------
# STEP 2: Set Graph Style
# -----------------------------------

sns.set_style("whitegrid")

# -----------------------------------
# GRAPH 1: House Price Distribution
# -----------------------------------

plt.figure(figsize=(10, 6))

sns.histplot(df["Price"], bins=30, kde=True)

plt.title("Distribution of House Prices")
plt.xlabel("House Price")
plt.ylabel("Number of Houses")

plt.show()


# -----------------------------------
# GRAPH 2: Square Feet vs Price
# -----------------------------------

plt.figure(figsize=(10, 6))

sns.scatterplot(
    x="Square_Feet",
    y="Price",
    data=df
)

plt.title("Square Feet vs House Price")
plt.xlabel("Square Feet")
plt.ylabel("Price")

plt.show()


# -----------------------------------
# GRAPH 3: Bedrooms vs Average Price
# -----------------------------------

plt.figure(figsize=(10, 6))

sns.barplot(
    x="Bedrooms",
    y="Price",
    data=df,
    estimator="mean"
)

plt.title("Average House Price by Number of Bedrooms")
plt.xlabel("Number of Bedrooms")
plt.ylabel("Average Price")

plt.show()


# -----------------------------------
# GRAPH 4: Location vs Average Price
# -----------------------------------

plt.figure(figsize=(10, 6))

sns.barplot(
    x="Location",
    y="Price",
    data=df,
    estimator="mean"
)

plt.title("Average House Price by Location")
plt.xlabel("Location")
plt.ylabel("Average Price")

plt.show()


# -----------------------------------
# GRAPH 5: Condition vs Average Price
# -----------------------------------

plt.figure(figsize=(10, 6))

sns.barplot(
    x="Condition",
    y="Price",
    data=df,
    estimator="mean"
)

plt.title("Average House Price by House Condition")
plt.xlabel("Condition")
plt.ylabel("Average Price")

plt.show()


# -----------------------------------
# GRAPH 6: Correlation Heatmap
# -----------------------------------

plt.figure(figsize=(10, 7))

numeric_data = df.select_dtypes(include=["int64", "float64"])

sns.heatmap(
    numeric_data.corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Between House Features")

plt.show()


# -----------------------------------
# GRAPH 7: Bathrooms vs Price
# -----------------------------------

plt.figure(figsize=(10, 6))

sns.boxplot(
    x="Bathrooms",
    y="Price",
    data=df
)

plt.title("Bathrooms vs House Price")
plt.xlabel("Number of Bathrooms")
plt.ylabel("Price")

plt.show()


print("\nData Visualization Completed Successfully!")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load dataset
df = pd.read_csv("house_price_prediction_dataset.csv")

# Create folder for graphs
os.makedirs("visualization_results", exist_ok=True)

sns.set_style("whitegrid")

# ---------------------------------------
# 1. Price Distribution
# ---------------------------------------

plt.figure(figsize=(10, 6))

sns.histplot(df["Price"], bins=30, kde=True)

plt.title("Distribution of House Prices")
plt.xlabel("Price")
plt.ylabel("Number of Houses")

plt.savefig(
    "visualization_results/price_distribution.png",
    bbox_inches="tight"
)

plt.close()


# ---------------------------------------
# 2. Square Feet vs Price
# ---------------------------------------

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=df,
    x="Square_Feet",
    y="Price"
)

plt.title("Square Feet vs House Price")

plt.savefig(
    "visualization_results/square_feet_vs_price.png",
    bbox_inches="tight"
)

plt.close()


# ---------------------------------------
# 3. Bedrooms vs Price
# ---------------------------------------

plt.figure(figsize=(10, 6))

sns.barplot(
    data=df,
    x="Bedrooms",
    y="Price",
    estimator="mean"
)

plt.title("Average Price by Bedrooms")

plt.savefig(
    "visualization_results/bedrooms_vs_price.png",
    bbox_inches="tight"
)

plt.close()


# ---------------------------------------
# 4. Location vs Price
# ---------------------------------------

plt.figure(figsize=(10, 6))

sns.barplot(
    data=df,
    x="Location",
    y="Price",
    estimator="mean"
)

plt.title("Average Price by Location")

plt.savefig(
    "visualization_results/location_vs_price.png",
    bbox_inches="tight"
)

plt.close()


# ---------------------------------------
# 5. Condition vs Price
# ---------------------------------------

plt.figure(figsize=(10, 6))

sns.barplot(
    data=df,
    x="Condition",
    y="Price",
    estimator="mean"
)

plt.title("Average Price by Condition")

plt.savefig(
    "visualization_results/condition_vs_price.png",
    bbox_inches="tight"
)

plt.close()


# ---------------------------------------
# 6. Correlation Heatmap
# ---------------------------------------

plt.figure(figsize=(10, 7))

numeric_data = df.select_dtypes(
    include=["int64", "float64"]
)

sns.heatmap(
    numeric_data.corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Feature Correlation Heatmap")

plt.savefig(
    "visualization_results/correlation_heatmap.png",
    bbox_inches="tight"
)

plt.close()


print("All graphs saved successfully!")

# ==========================================
# TASK TA-010: Feature Preparation
# Deliverable: ML-ready Dataset
# ==========================================
from sklearn.preprocessing import StandardScaler

# 1. Drop non-predictive identifier column
df_clean = df.drop(columns=['House_ID'], errors='ignore')

# 2. Separate Target (y) and Features (X)
y = df_clean['Price']
X = df_clean.drop(columns=['Price'])

# 3. Encode categorical features into dummy columns
X = pd.get_dummies(X, drop_first=True)

# 4. Scale numerical columns
num_cols = X.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

# 5. Export ML-ready dataset (Task 10 Deliverable)
ml_ready_df = pd.concat([X, y.reset_index(drop=True)], axis=1)
ml_ready_df.to_csv("ml_ready_dataset.csv", index=False)

print("\n--- Task TA-010 Complete ---")
print("ML-ready dataset saved successfully as 'ml_ready_dataset.csv'!")
print(f"Features shape: {X.shape}, Target shape: {y.shape}")